import { http } from './httpClient';

/** Formatea segundos como "12 h 34 min" o "34 min". */
export function formatHours(seconds: number): string {
  const totalMinutes = Math.round(seconds / 60);
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  return hours > 0 ? `${hours} h ${minutes} min` : `${minutes} min`;
}

export interface TopListener {
  userId: string;
  displayName: string;
  email: string;
  streams: number;
  seconds: number;
  /** 0–1: proporción de segundos estimados en vez de medidos. */
  estimatedShare: number;
  lastPlayedAt: string;
}

export interface TopArtistByTime {
  artistId: string;
  name: string;
  imageUrl: string;
  isVerified: boolean;
  streams: number;
  seconds: number;
  listeners: number;
  estimatedShare: number;
}

export interface TrendingRow {
  trackId: string;
  title: string;
  coverUrl: string;
  duration: number;
  genre: string | null;
  bpm: number | null;
  artistId: string;
  artistName: string;
  artistImageUrl: string;
  isVerified: boolean;
  streams: number;
  listeners: number;
  seconds: number;
}

export interface TopSearch {
  normalized: string;
  sample: string;
  searches: number;
  avgResults: number;
}

export type SignupStage = 'VALIDATION' | 'DUPLICATE_EMAIL' | 'GOOGLE_OAUTH' | 'SERVER_ERROR';

export const SIGNUP_STAGE_LABELS: Record<SignupStage, string> = {
  VALIDATION: 'Formulario inválido',
  DUPLICATE_EMAIL: 'Correo ya registrado',
  GOOGLE_OAUTH: 'Falló Google',
  SERVER_ERROR: 'Error del servidor',
};

export interface SignupAttempt {
  id: string;
  email: string | null;
  stage: SignupStage;
  reason: string;
  ipAddress: string | null;
  createdAt: string;
}

export const fetchTrending = (days = 7) =>
  http.get<{ windowDays: number; top1: TrendingRow | null; tracks: TrendingRow[] }>(`/admin/trending?days=${days}`);

export const fetchTopListeners = (order: 'desc' | 'asc' = 'desc') =>
  http.get<{ windowDays: number; listeners: TopListener[] }>(`/admin/audience/listeners?order=${order}`);

export const fetchTopArtists = () =>
  http.get<{ windowDays: number; artists: TopArtistByTime[] }>('/admin/audience/artists');

export const fetchTopSearches = () =>
  http.get<{ windowDays: number; searches: TopSearch[]; withoutResults: TopSearch[] }>('/admin/audience/searches');

export const fetchSignupFailures = () =>
  http.get<{ byStage: Partial<Record<SignupStage, number>>; attempts: SignupAttempt[] }>(
    '/admin/audience/signup-failures?limit=30',
  );

export interface AdminPlaylist {
  id: string;
  title: string;
  description: string | null;
  coverUrl: string | null;
  isPublic: boolean;
  isAutoGenerated: boolean;
  isBlocked: boolean;
  blockedReason: string | null;
  updatedAt: string;
  owner: { id: string; displayName: string; email: string };
  _count: { tracks: number };
}

/** Totales de TODO el catálogo, no de la página ni del filtro de búsqueda. */
export interface PlaylistSummary {
  total: number;
  publicas: number;
  privadas: number;
  bloqueadas: number;
  automaticas: number;
}

export const fetchPlaylists = (search = '') => {
  const q = search.trim() ? `&search=${encodeURIComponent(search.trim())}` : '';
  return http.get<{ playlists: AdminPlaylist[]; summary: PlaylistSummary; pagination: { total: number } }>(
    `/admin/playlists?limit=50${q}`,
  );
};

/** Alternativa reversible a borrar: la retira de lo público sin destruirla. */
export const setPlaylistBlocked = (id: string, isBlocked: boolean, reason?: string) =>
  http.patch<{ playlist: AdminPlaylist }>(`/admin/playlists/${id}/block`, {
    isBlocked,
    ...(reason ? { reason } : {}),
  });

export const deletePlaylist = (id: string) => http.delete<{ message: string }>(`/admin/playlists/${id}`);

export interface MusicGenre {
  id: string;
  name: string;
  slug: string;
  color: string;
  isActive: boolean;
  position: number;
  artistCount: number;
}

export const fetchGenres = () => http.get<{ genres: MusicGenre[] }>('/admin/genres');
export const createGenre = (data: { name: string; color?: string; position?: number }) =>
  http.post<{ genre: MusicGenre }>('/admin/genres', data);
export const updateGenre = (id: string, data: Partial<{ name: string; color: string; isActive: boolean; position: number }>) =>
  http.patch<{ genre: MusicGenre }>(`/admin/genres/${id}`, data);
export const deleteGenre = (id: string) => http.delete<{ message: string }>(`/admin/genres/${id}`);

export interface AppSetting {
  key: string;
  label: string;
  description: string;
  type: 'boolean' | 'number' | 'string';
  value: string;
  defaultValue: string;
  isDefault: boolean;
  group: string;
  updatedAt: string | null;
}

export const fetchSettings = () => http.get<{ settings: AppSetting[] }>('/admin/settings');
export const updateSetting = (key: string, value: string) =>
  http.patch<{ settings: AppSetting[] }>('/admin/settings', { key, value });

export interface AdminPlaylistTrack {
  id: string;
  position: number;
  title: string;
  coverUrl: string;
  duration: number;
  genre: string | null;
  status: string;
  isBlocked: boolean;
  playCount: number;
  artist: { id: string; name: string };
}

export interface AdminPlaylistDetail {
  playlist: AdminPlaylist;
  totalTracks: number;
  /**
   * Suma de las reproducciones de las canciones de la lista.
   *
   * Cuenta TODAS las escuchas de cada pista en la plataforma, no sólo las
   * que se lanzaron desde esta playlist: `StreamLog` guarda qué sonó y
   * quién la puso, no desde qué pantalla. Sirve para pesar el repertorio
   * que alguien reunió, no para atribuirle escuchas a la lista.
   */
  totalPlays: number;
  totalSeconds: number;
  tracks: AdminPlaylistTrack[];
}

export const fetchPlaylistDetail = (id: string) => http.get<AdminPlaylistDetail>(`/admin/playlists/${id}`);
