import { Link } from 'react-router-dom';
import { useCallback, useEffect, useState } from 'react';
import { Trash2, Lock, Globe, Sparkles, Download, ShieldOff, ShieldCheck } from 'lucide-react';
import { AdminShell } from '../components/AdminShell';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { CoverImage } from '../components/CoverImage';
import { fetchPlaylists, deletePlaylist, setPlaylistBlocked, type AdminPlaylist, type PlaylistSummary } from '../lib/audience';
import { toCsv, downloadCsv, datedFilename } from '../lib/csv';

/**
 * Todas las playlists de la plataforma, con opción de eliminarlas.
 *
 * Borrar contenido ajeno queda en la bitácora con el nombre y el dueño: si
 * alguien reclama, tiene que poder verse quién la borró y cuándo.
 */
export function PlaylistsPage() {
  const [playlists, setPlaylists] = useState<AdminPlaylist[]>([]);
  const [total, setTotal] = useState(0);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [pendingDelete, setPendingDelete] = useState<AdminPlaylist | null>(null);
  const [summary, setSummary] = useState<PlaylistSummary | null>(null);

  const load = useCallback((term: string) => {
    fetchPlaylists(term)
      .then((res) => {
        setPlaylists(res.playlists);
        setSummary(res.summary);
        setTotal(res.pagination.total);
        setError(null);
      })
      .catch((err: unknown) => setError(err instanceof Error ? err.message : 'No se pudieron cargar las playlists.'))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    const timer = setTimeout(() => load(search), 250);
    return () => clearTimeout(timer);
  }, [search, load]);

  /**
   * Bloquear en vez de borrar.
   *
   * Es reversible: la playlist sale de lo público pero su dueño no pierde
   * el trabajo de haberla armado, y si la reclamación era infundada se
   * restaura con otro clic. Borrar no tiene vuelta atrás.
   */
  const handleToggleBlock = async (playlist: AdminPlaylist) => {
    setBusyId(playlist.id);
    try {
      await setPlaylistBlocked(playlist.id, !playlist.isBlocked);
      load(search);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'No se pudo cambiar el bloqueo.');
    } finally {
      setBusyId(null);
    }
  };

  const handleDelete = async (playlist: AdminPlaylist) => {
    setBusyId(playlist.id);
    try {
      await deletePlaylist(playlist.id);
      setPendingDelete(null);
      load(search);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'No se pudo eliminar.');
    } finally {
      setBusyId(null);
    }
  };

  return (
    <AdminShell
      title="Playlists"
      subtitle={`${total} lista(s) creada(s) por los usuarios`}
      actions={
        <button
          type="button"
          disabled={playlists.length === 0}
          onClick={() =>
            downloadCsv(
              datedFilename('playlists'),
              toCsv(playlists, [
                { header: 'Titulo', value: (r) => r.title },
                { header: 'Canciones', value: (r) => r._count.tracks },
                { header: 'Duenio', value: (r) => r.owner.displayName },
                { header: 'Correo', value: (r) => r.owner.email },
                { header: 'Publica', value: (r) => (r.isPublic ? 'si' : 'no') },
                { header: 'Automatica', value: (r) => (r.isAutoGenerated ? 'si' : 'no') },
              ]),
            )
          }
          className="flex items-center gap-2 rounded-full border border-white/20 px-3 py-1.5 text-sm font-semibold transition-colors hover:border-white disabled:opacity-40"
        >
          <Download size={14} aria-hidden />
          <span className="hidden sm:inline">Exportar CSV</span>
        </button>
      }
    >
      {error && (
        <p role="alert" className="mb-6 rounded-xl bg-danger/10 px-4 py-3 text-sm font-semibold text-danger">
          {error}
        </p>
      )}

      {/*
        Los totales son de TODA la plataforma, no del filtro: si cambiaran al
        teclear en el buscador dejarían de servir para lo que están.
      */}
      {summary && (
        <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-5">
          <SummaryTile label="Total" value={summary.total} />
          <SummaryTile label="Públicas" value={summary.publicas} />
          <SummaryTile label="Privadas" value={summary.privadas} />
          <SummaryTile label="Bloqueadas" value={summary.bloqueadas} tone={summary.bloqueadas > 0 ? 'danger' : undefined} />
          <SummaryTile label="Automáticas" value={summary.automaticas} />
        </div>
      )}

      <input
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        placeholder="Buscar por nombre de la lista…"
        className="mb-6 w-full max-w-md rounded-lg border border-white/15 bg-black/20 px-4 py-2.5 text-sm outline-none focus:border-brand"
      />

      {loading ? (
        <div className="flex flex-col gap-2">
          {[...Array(5)].map((_, i) => (
            <div key={i} className="h-20 animate-pulse rounded-xl border border-white/10 bg-surface" />
          ))}
        </div>
      ) : playlists.length === 0 ? (
        <p className="rounded-xl border border-dashed border-white/15 px-5 py-12 text-center text-sm text-muted">
          No hay playlists que coincidan.
        </p>
      ) : (
        <ul className="flex flex-col gap-2">
          {playlists.map((playlist) => (
            <li
              key={playlist.id}
              className="flex flex-wrap items-center gap-4 rounded-xl border border-white/10 bg-surface p-3"
            >
              <CoverImage src={playlist.coverUrl ?? ''} alt={playlist.title} size={56} rounded="rounded-lg" />

              <div className="min-w-0 flex-1">
                <p className="flex items-center gap-2 truncate text-sm font-semibold">
                  {/* El título abre el detalle: canciones y reproducciones. */}
                  <Link to={`/playlists/${playlist.id}`} className="truncate hover:underline">
                    {playlist.title}
                  </Link>
                  {playlist.isAutoGenerated && (
                    <span
                      className="flex items-center gap-1 rounded-full bg-sky-500/15 px-2 py-0.5 text-[10px] font-bold text-sky-300"
                      title="Generada por el motor de recomendaciones"
                    >
                      <Sparkles size={10} aria-hidden />
                      AUTO
                    </span>
                  )}
                  {playlist.isPublic ? (
                    <Globe size={13} className="shrink-0 text-muted" aria-label="Pública" />
                  ) : (
                    <Lock size={13} className="shrink-0 text-muted" aria-label="Privada" />
                  )}
                  {playlist.isBlocked && (
                    <span
                      className="flex items-center gap-1 rounded-full bg-danger/15 px-2 py-0.5 text-[10px] font-bold text-danger"
                      title={playlist.blockedReason ?? 'Retirada por moderación'}
                    >
                      <ShieldOff size={10} aria-hidden />
                      BLOQUEADA
                    </span>
                  )}
                </p>
                <p className="truncate text-xs text-muted">
                  {playlist._count.tracks} canción(es) · {playlist.owner.displayName} ({playlist.owner.email})
                </p>
              </div>

              {/* Bloquear va primero y borrar después, en ese orden y con
                  ese contraste: lo reversible es lo que debería pulsarse por
                  defecto, y lo irreversible tiene que costar un poco más. */}
              <button
                type="button"
                onClick={() => void handleToggleBlock(playlist)}
                disabled={busyId === playlist.id}
                className="flex w-28 shrink-0 items-center justify-center gap-1.5 rounded-full border border-white/25 px-3.5 py-1.5 text-xs font-semibold transition-colors hover:border-white disabled:opacity-50"
              >
                {playlist.isBlocked ? <ShieldCheck size={13} aria-hidden /> : <ShieldOff size={13} aria-hidden />}
                {playlist.isBlocked ? 'Restaurar' : 'Bloquear'}
              </button>

              <button
                type="button"
                onClick={() => setPendingDelete(playlist)}
                disabled={busyId === playlist.id}
                className="flex w-28 shrink-0 items-center justify-center gap-1.5 rounded-full border border-danger/50 px-3.5 py-1.5 text-xs font-semibold text-danger transition-colors hover:border-danger disabled:opacity-50"
              >
                <Trash2 size={13} aria-hidden />
                Eliminar
              </button>
            </li>
          ))}
        </ul>
      )}

      {pendingDelete && (
        <ConfirmDialog
          title={`Cancelar "${pendingDelete.title}"`}
          message={`La lista de ${pendingDelete.owner.displayName} y sus ${pendingDelete._count.tracks} canción(es) dejan de existir. Las canciones NO se borran del catálogo, sólo la lista. No se puede deshacer.`}
          confirmLabel="Eliminar la lista"
          isSubmitting={busyId === pendingDelete.id}
          onCancel={() => setPendingDelete(null)}
          onConfirm={() => handleDelete(pendingDelete)}
        />
      )}
    </AdminShell>
  );
}

function SummaryTile({ label, value, tone }: { label: string; value: number; tone?: 'danger' }) {
  return (
    <div className="rounded-xl border border-white/10 bg-surface px-4 py-3">
      <p className={`text-2xl font-extrabold tabular-nums ${tone === 'danger' ? 'text-danger' : ''}`}>{value}</p>
      <p className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</p>
    </div>
  );
}
