import { useCallback, useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Play, Lock, Globe, Sparkles, ShieldOff, Clock, Music } from 'lucide-react';
import { AdminShell } from '../components/AdminShell';
import { CoverImage } from '../components/CoverImage';
import { fetchPlaylistDetail, type AdminPlaylistDetail } from '../lib/audience';
import { formatDuration, formatHoursMinutes } from '../lib/format';

/**
 * Detalle de una playlist de usuario.
 *
 * Responde a lo que hace falta para juzgarla de un vistazo: cuántas
 * canciones reúne, cuánto se escucha cada una y cuánto suman entre todas.
 */

export function PlaylistDetailPage() {
  const { id = '' } = useParams<{ id: string }>();

  const [data, setData] = useState<AdminPlaylistDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(() => {
    fetchPlaylistDetail(id)
      .then((res) => {
        setData(res);
        setError(null);
      })
      .catch((err: unknown) => setError(err instanceof Error ? err.message : 'No se pudo cargar la playlist.'))
      .finally(() => setLoading(false));
  }, [id]);

  useEffect(load, [load]);

  if (loading) {
    return (
      <AdminShell title="Playlist" subtitle="Cargando…">
        <div className="h-40 animate-pulse rounded-xl border border-white/10 bg-surface" />
      </AdminShell>
    );
  }

  if (!data) {
    return (
      <AdminShell title="Playlist" subtitle="No disponible">
        <p role="alert" className="rounded-xl bg-danger/10 px-4 py-3 text-sm font-semibold text-danger">
          {error ?? 'No encontrada.'}
        </p>
      </AdminShell>
    );
  }

  const { playlist, tracks, totalTracks, totalPlays, totalSeconds } = data;
  // La más escuchada, para destacarla en la lista: es lo que sostiene el
  // interés de la playlist entera.
  const topPlays = Math.max(0, ...tracks.map((t) => t.playCount));

  return (
    <AdminShell
      title={playlist.title}
      subtitle={`De ${playlist.owner.displayName}`}
      actions={
        <Link
          to="/playlists"
          className="flex items-center gap-2 rounded-full border border-white/20 px-3 py-1.5 text-sm font-semibold transition-colors hover:border-white"
        >
          <ArrowLeft size={14} aria-hidden />
          <span className="hidden sm:inline">Playlists</span>
        </Link>
      }
    >
      <header className="mb-6 flex flex-wrap items-center gap-5 rounded-xl border border-white/10 bg-surface p-5">
        <CoverImage src={playlist.coverUrl ?? ''} alt={playlist.title} size={96} rounded="rounded-lg" />
        <div className="min-w-0 flex-1">
          <p className="flex flex-wrap items-center gap-2 text-2xl font-extrabold">
            {playlist.title}
            {playlist.isPublic ? (
              <Globe size={16} className="text-muted" aria-label="Pública" />
            ) : (
              <Lock size={16} className="text-muted" aria-label="Privada" />
            )}
            {playlist.isAutoGenerated && (
              <span className="flex items-center gap-1 rounded-full bg-sky-500/15 px-2 py-0.5 text-[10px] font-bold text-sky-300">
                <Sparkles size={10} aria-hidden />
                AUTO
              </span>
            )}
            {playlist.isBlocked && (
              <span
                className="flex items-center gap-1 rounded-full bg-danger/15 px-2 py-0.5 text-[10px] font-bold text-danger"
                title={playlist.blockedReason ?? 'Retirada por moderación'}
              >
                <ShieldOff size={10} aria-hidden />
                BLOQUEADA
              </span>
            )}
          </p>
          <p className="mt-1 text-sm text-muted">
            {playlist.owner.displayName} · {playlist.owner.email}
          </p>
          {playlist.description && <p className="mt-2 max-w-2xl text-sm text-muted">{playlist.description}</p>}
        </div>
      </header>

      <div className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-3">
        <Tile icon={<Music size={16} aria-hidden />} label="Canciones" value={totalTracks.toLocaleString('es')} />
        <Tile icon={<Play size={16} aria-hidden />} label="Reproducciones" value={totalPlays.toLocaleString('es')} />
        <Tile icon={<Clock size={16} aria-hidden />} label="Duración" value={formatHoursMinutes(totalSeconds)} />
      </div>

      {/*
        Qué mide exactamente el total. Sin esta aclaración es fácil leerlo
        como "escuchas que vinieron de esta playlist", que sería otra cosa.
      */}
      <p className="mb-6 rounded-lg border border-white/10 bg-black/20 px-4 py-3 text-xs text-muted">
        Las reproducciones son las totales de cada canción en la plataforma, no sólo las lanzadas desde esta lista:
        el registro de escuchas guarda qué sonó y quién la puso, no desde qué pantalla se abrió.
      </p>

      {tracks.length === 0 ? (
        <p className="rounded-xl border border-dashed border-white/15 px-5 py-12 text-center text-sm text-muted">
          Esta playlist está vacía.
        </p>
      ) : (
        <ul className="flex flex-col gap-2">
          {tracks.map((track) => (
            <li
              key={track.id}
              className="flex flex-wrap items-center gap-4 rounded-xl border border-white/10 bg-surface p-3"
            >
              <span className="w-6 shrink-0 text-center text-sm tabular-nums text-muted">{track.position + 1}</span>
              <CoverImage src={track.coverUrl} alt={track.title} size={48} rounded="rounded-md" />

              <div className="min-w-0 flex-1">
                <p className="flex items-center gap-2 truncate text-sm font-semibold">
                  {track.title}
                  {track.isBlocked && (
                    <span className="rounded-full bg-danger/15 px-2 py-0.5 text-[10px] font-bold text-danger">
                      BLOQUEADA
                    </span>
                  )}
                </p>
                <p className="truncate text-xs text-muted">
                  <Link to={`/artists/${track.artist.id}`} className="hover:underline">
                    {track.artist.name}
                  </Link>
                  {' · '}
                  {formatDuration(track.duration)}
                  {track.genre && ` · ${track.genre}`}
                </p>
              </div>

              <div className="flex w-32 shrink-0 flex-col gap-1">
                <p className="flex items-center justify-end gap-1.5 text-xs font-semibold tabular-nums">
                  <Play size={11} aria-hidden className="text-muted" />
                  {track.playCount.toLocaleString('es')}
                </p>
                {/* Barra relativa a la más escuchada de la lista: de un vistazo
                    se ve si el interés está repartido o lo sostiene una sola. */}
                <span className="h-1 overflow-hidden rounded-full bg-white/10">
                  <span
                    className="block h-full rounded-full bg-brand"
                    style={{ width: topPlays > 0 ? `${(track.playCount / topPlays) * 100}%` : '0%' }}
                  />
                </span>
              </div>
            </li>
          ))}
        </ul>
      )}
    </AdminShell>
  );
}

function Tile({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="rounded-xl border border-white/10 bg-surface px-4 py-3">
      <p className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide text-muted">
        {icon}
        {label}
      </p>
      <p className="mt-1 text-2xl font-extrabold tabular-nums">{value}</p>
    </div>
  );
}
