/**
 * Peyma Music API — Motor de recomendaciones por ritmo/estilo
 *
 * A diferencia de `audioAnalysis.ts` (que hoy es un placeholder), esto SÍ es
 * el algoritmo real: agrupa/ordena pistas por distancia de coseno entre sus
 * `featureVector` (ver `AudioAnalysis`). Funciona igual de bien con
 * features reales el día que `audioAnalyzer` deje de ser heurístico — el
 * match por vector no le importa de dónde salieron los números.
 */
import { prisma } from '../prismaClient';
import type { Genre, PlaylistGeneratorType, Prisma } from '@prisma/client';

const SIMILAR_TRACKS_LIMIT_DEFAULT = 20;
/** Cuántas pistas recientes/favoritas del usuario entran al cálculo del "centroide" de gustos. */
const HISTORY_SAMPLE_SIZE = 30;

export function cosineSimilarity(a: readonly number[], b: readonly number[]): number {
  if (a.length !== b.length || a.length === 0) return 0;
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i]! * b[i]!;
    normA += a[i]! * a[i]!;
    normB += b[i]! * b[i]!;
  }
  if (normA === 0 || normB === 0) return 0;
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

/** Promedio dimensión a dimensión — el "centroide" de un conjunto de vectores de features. */
export function centroid(vectors: readonly (readonly number[])[]): number[] | null {
  if (vectors.length === 0) return null;
  const dims = vectors[0]!.length;
  const sums = new Array(dims).fill(0);
  for (const vector of vectors) {
    for (let i = 0; i < dims; i++) sums[i] += vector[i] ?? 0;
  }
  return sums.map((sum) => sum / vectors.length);
}

const TRACK_WITH_ANALYSIS = {
  include: {
    artist: { select: { id: true, name: true, imageUrl: true, isVerified: true } },
    album: { select: { id: true, title: true, coverUrl: true } },
    analysis: true,
  },
} satisfies Prisma.TrackDefaultArgs;

export type TrackWithAnalysis = Prisma.TrackGetPayload<typeof TRACK_WITH_ANALYSIS>;

/** Pistas "parecidas" a una dada — misma idea que "porque te gustó X" en Spotify/Apple Music. */
export async function findSimilarTracks(trackId: string, limit = SIMILAR_TRACKS_LIMIT_DEFAULT): Promise<{ track: TrackWithAnalysis; similarity: number }[]> {
  const seed = await prisma.track.findUnique({ where: { id: trackId }, include: { analysis: true } });
  if (!seed?.analysis) return [];

  // No hay pgvector acá (sería la optimización natural a gran escala): con
  // el tamaño de catálogo esperado en este paso, traer todo lo analizado y
  // rankear en memoria es simple, correcto y rápido de verdad.
  const candidates = await prisma.track.findMany({
    where: { id: { not: trackId }, analysis: { isNot: null }, status: 'APPROVED', artist: { isBlocked: false } },
    ...TRACK_WITH_ANALYSIS,
  });

  return candidates
    .map((track) => ({ track, similarity: cosineSimilarity(seed.analysis!.featureVector, track.analysis!.featureVector) }))
    .sort((a, b) => b.similarity - a.similarity)
    .slice(0, limit);
}

/**
 * "Para ti": centroide del historial de escucha (recientes + favoritas) del
 * usuario, comparado contra todo lo analizado que todavía no escuchó. Sin
 * historial suficiente, devuelve `[]` — el caller decide el fallback
 * (p. ej. un catálogo general), este servicio no inventa datos que no tiene.
 */
export async function recommendForUser(userId: string, limit = SIMILAR_TRACKS_LIMIT_DEFAULT): Promise<{ track: TrackWithAnalysis; similarity: number }[]> {
  const [recentlyPlayed, favorites] = await Promise.all([
    prisma.recentlyPlayed.findMany({
      where: { userId },
      orderBy: { playedAt: 'desc' },
      take: HISTORY_SAMPLE_SIZE,
      include: { track: { include: { analysis: true } } },
    }),
    prisma.favorite.findMany({
      where: { userId },
      take: HISTORY_SAMPLE_SIZE,
      include: { track: { include: { analysis: true } } },
    }),
  ]);

  const historyTrackIds = new Set<string>();
  const vectors: number[][] = [];
  for (const entry of [...recentlyPlayed, ...favorites]) {
    historyTrackIds.add(entry.track.id);
    if (entry.track.analysis) vectors.push(entry.track.analysis.featureVector);
  }

  const userTaste = centroid(vectors);
  if (!userTaste) return [];

  const candidates = await prisma.track.findMany({
    where: { id: { notIn: Array.from(historyTrackIds) }, analysis: { isNot: null }, status: 'APPROVED', artist: { isBlocked: false } },
    ...TRACK_WITH_ANALYSIS,
  });

  return candidates
    .map((track) => ({ track, similarity: cosineSimilarity(userTaste, track.analysis!.featureVector) }))
    .sort((a, b) => b.similarity - a.similarity)
    .slice(0, limit);
}

const GENERATED_PLAYLIST_SIZE = 20;

/**
 * Materializa una recomendación como una `Playlist` real y persistida
 * (`isAutoGenerated: true`) — la "Daily Mix"/"Mezcla por ritmo" que el
 * usuario ve en su biblioteca, no sólo una respuesta efímera de la API.
 */
export async function generateAutoPlaylist(
  userId: string,
  type: PlaylistGeneratorType,
  options: { seedTrackId?: string; genre?: Genre } = {},
) {
  const user = await prisma.user.findUniqueOrThrow({ where: { id: userId }, select: { displayName: true } });

  let trackIds: string[] = [];
  let title = 'Mezcla para ti';
  let description = 'Generada automáticamente a partir de lo que escuchas';

  if (type === 'RHYTHM_MATCH' && options.seedTrackId) {
    const similar = await findSimilarTracks(options.seedTrackId, GENERATED_PLAYLIST_SIZE);
    trackIds = similar.map((s) => s.track.id);
    title = 'Mezcla por ritmo';
    description = 'Pistas con un ritmo y una energía parecidos';
  } else if (type === 'GENRE_MIX' && options.genre) {
    const tracks = await prisma.track.findMany({
      where: { genre: options.genre, status: 'APPROVED', artist: { isBlocked: false } },
      take: GENERATED_PLAYLIST_SIZE,
      orderBy: { createdAt: 'desc' },
    });
    trackIds = tracks.map((t) => t.id);
    title = `Mezcla ${options.genre}`;
    description = `Lo último en ${options.genre}`;
  } else {
    const recommended = await recommendForUser(userId, GENERATED_PLAYLIST_SIZE);
    trackIds = recommended.map((r) => r.track.id);
    title = `Mix diario de ${user.displayName}`;
  }

  return prisma.playlist.create({
    data: {
      title,
      description,
      ownerId: userId,
      isPublic: false,
      isAutoGenerated: true,
      generatorType: type,
      seedUserId: userId,
      generationCriteria: { ...options, generatedAt: new Date().toISOString() },
      tracks: {
        create: trackIds.map((trackId, position) => ({ trackId, position })),
      },
    },
    include: {
      tracks: { orderBy: { position: 'asc' }, include: { track: true } },
    },
  });
}
